# Generated by Django 4.1.5 on 2023-05-10 12:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plateDetection', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='userName',
            new_name='student_name',
        ),
        migrations.AddField(
            model_name='user',
            name='entered_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='left_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
