# Generated by Django 4.1.5 on 2023-05-11 06:27

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plateDetection', '0002_rename_username_user_student_name_user_entered_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_num', models.TextField()),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='entered_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='left_at',
        ),
        migrations.AddField(
            model_name='user',
            name='erp',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='plate_num',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='program',
            field=models.TextField(default=datetime.datetime(2023, 5, 11, 6, 27, 0, 922005, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
